// In-game tests for Pawn Diary's PUBLIC integration API surface + the settings gates in front of it
// (TEST_COVERAGE_PLAN.md §7.1: settings + external API). Companion to PawnDiaryExternalApiFlowTests,
// which proves the SubmitEvent RECORD path end to end. This suite instead exercises the rest of the
// PawnDiary.Integration.PawnDiaryApi facade — the readiness/eligibility probes, the per-pawn
// generation toggle, the source-owned writing-style and psychotype override setters, the process-global
// entry-status listener + pawn-context provider registries, and the three submit routes — and for each
// public call covers three shapes: a null/blank argument (returns safely, never throws, records no
// state), an INELIGIBLE pawn (rejected), and a VALID call with an observable outcome. It also proves the
// player's master integration toggle (allowExternalIntegrations) gates the matching capture route and is
// restored afterwards.
//
// Determinism / safety notes for this row:
//   - External integrations are force-enabled in SetUp and restored in teardown (via RegisterCleanup),
//     so the developer's real setting is untouched. Tests that flip the master switch mid-body set it
//     back inline as well.
//   - The "eligible" colonist is a normal generation-DISABLED harness pawn that is then made
//     integration-eligible through the public SetDiaryGenerationEnabled toggle (not by firing anything),
//     so no event is created and no LLM request can ever leave the game. Enabling the flag on a pawn with
//     no diary events queues no generation work.
//   - The "ineligible" pawn is a factionless (non-colonist) humanlike adult: it fails Pawn Diary's base
//     owner eligibility, so EVERY gated call rejects it uniformly and none of them can materialize a
//     diary record for it. It is generated by this suite (not the harness) and destroyed in teardown.
//   - Every call is made on the main thread (RimTest runs on it); the API's off-thread guards are not
//     exercised here.
//   - RegisterPawnContextProvider has no public unregister (the runtime registry is add/replace only), so
//     this suite only asserts its leak-free reject-invalid-input guards and deliberately does NOT perform
//     a live registration that would persist into the developer's process. See gotchas in the report.
//
// Coverage-matrix area (TEST_COVERAGE_PLAN.md §7.1): integration API surface + settings gates.
using System;
using PawnDiary.Integration;
using RimTestRedux;
using RimWorld;
using Verse;

namespace PawnDiary.RimTests
{
    /// <summary>
    /// Proves Pawn Diary's public integration API surface behaves at its edges: readiness/eligibility
    /// probes reflect the loaded game and the master toggle, the per-pawn generation toggle round-trips
    /// observably, the source-owned writing-style/psychotype override setters accept a valid write and
    /// reject null/blank/ineligible input, the listener registry registers and unregisters cleanly, the
    /// context-provider registry rejects invalid input without leaking, and the submit routes swallow a
    /// null request without recording anything. These require a loaded game because the API's readiness
    /// gate (IsReady) is false at the main menu; no test enables an actual generation run, so no LLM
    /// request can leave the game.
    /// </summary>
    [TestSuite]
    public static class PawnDiaryApiSurfaceFixtureTests
    {
        private const string TestSourceId = "pawndiary.rimtest.apisurface";
        private const string StyleRule = "Writes in short, plain sentences.";
        private const string PsychotypeRule = "Notices the small kindnesses in a hard day.";

        private static PawnDiaryRimTestScope scope;

        // Generation-DISABLED harness colonist that this suite promotes to integration-eligible via the
        // public toggle. Cleaned by the harness (it is a scope pawn).
        private static Pawn eligiblePawn;

        // Factionless humanlike adult: base-ineligible, so every gated call rejects it. Generated and
        // destroyed by this suite (not tracked by the harness), and it never accrues diary state.
        private static Pawn ineligiblePawn;

        /// <summary>
        /// Opens a fresh scope, force-enables the external-integration master switch (snapshotted and
        /// restored in teardown), builds one integration-eligible colonist and one base-ineligible pawn.
        /// </summary>
        [BeforeEach]
        public static void SetUp()
        {
            scope = PawnDiaryRimTestScope.Begin();

            PawnDiarySettings settings = PawnDiaryMod.Settings;
            if (settings == null)
            {
                throw new AssertionException("Pawn Diary settings must be loaded before the API surface suite runs.");
            }

            bool originalAllow = settings.allowExternalIntegrations;
            settings.allowExternalIntegrations = true;
            scope.RegisterCleanup(() => settings.allowExternalIntegrations = originalAllow);

            // A generation-disabled colonist is base-eligible but NOT integration-eligible; promote it
            // through the public toggle so the "valid" cases below have an integration-eligible pawn.
            eligiblePawn = scope.CreateAdultColonist();
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.SetDiaryGenerationEnabled(eligiblePawn, true),
                "SetUp could not enable diary generation on the eligible test colonist.");

            ineligiblePawn = CreateIneligiblePawn();
        }

        /// <summary>
        /// Restores every mutation (master switch, per-pawn state, the extra ineligible pawn) and audits
        /// that no test-owned event, diary, or registry entry survived — even when a test above threw.
        /// </summary>
        [AfterEach]
        public static void TearDown()
        {
            try
            {
                scope?.TearDown();
            }
            finally
            {
                scope = null;
                eligiblePawn = null;
                ineligiblePawn = null;
            }
        }

        /// <summary>
        /// §7.1. IsReady is true in a loaded game and IsExternalApiEnabled tracks the player's master
        /// integration toggle: it reads true while enabled and false the instant the switch is off. The
        /// switch is set back to enabled inline (and again in teardown).
        /// </summary>
        [Test]
        public static void ReadinessAndMasterToggleReflectSettings()
        {
            PawnDiarySettings settings = PawnDiaryMod.Settings;

            PawnDiaryRimTestScope.Require(PawnDiaryApi.IsReady, "IsReady should be true in a loaded game.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsExternalApiEnabled,
                "IsExternalApiEnabled should be true while the master integration switch is on.");

            settings.allowExternalIntegrations = false;
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsExternalApiEnabled,
                "IsExternalApiEnabled should be false while the master integration switch is off.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsReady,
                "IsReady reflects the loaded game only and should not be affected by the master switch.");

            settings.allowExternalIntegrations = true;
        }

        /// <summary>
        /// §7.1. IsDiaryEligible: null pawn is false, a base-ineligible pawn is false, an
        /// integration-eligible colonist is true, and turning the master switch off gates it back to
        /// false (the top-level player gate over the whole read surface).
        /// </summary>
        [Test]
        public static void IsDiaryEligibleCoversNullIneligibleValidAndGate()
        {
            PawnDiarySettings settings = PawnDiaryMod.Settings;

            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsDiaryEligible(null), "IsDiaryEligible(null) should be false.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsDiaryEligible(ineligiblePawn),
                "IsDiaryEligible should be false for a base-ineligible (factionless) pawn.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsDiaryEligible(eligiblePawn),
                "IsDiaryEligible should be true for an integration-eligible colonist.");

            settings.allowExternalIntegrations = false;
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsDiaryEligible(eligiblePawn),
                "IsDiaryEligible should be gated to false while the master integration switch is off.");
            settings.allowExternalIntegrations = true;
        }

        /// <summary>
        /// §7.1. IsDiaryGenerationEnabled: null pawn is false, a base-ineligible pawn is false, an
        /// integration-eligible colonist reads true, and the master switch gates it back to false.
        /// </summary>
        [Test]
        public static void IsDiaryGenerationEnabledCoversNullIneligibleValidAndGate()
        {
            PawnDiarySettings settings = PawnDiaryMod.Settings;

            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsDiaryGenerationEnabled(null), "IsDiaryGenerationEnabled(null) should be false.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsDiaryGenerationEnabled(ineligiblePawn),
                "IsDiaryGenerationEnabled should be false for a base-ineligible pawn.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsDiaryGenerationEnabled(eligiblePawn),
                "IsDiaryGenerationEnabled should be true for the enabled eligible colonist.");

            settings.allowExternalIntegrations = false;
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsDiaryGenerationEnabled(eligiblePawn),
                "IsDiaryGenerationEnabled should be gated to false while the master switch is off.");
            settings.allowExternalIntegrations = true;
        }

        /// <summary>
        /// §7.1. SetDiaryGenerationEnabled: null pawn and base-ineligible pawn both fail; on the eligible
        /// colonist the flag round-trips observably through IsDiaryGenerationEnabled; and with the master
        /// switch off the write is refused and leaves the saved flag unchanged (proven after re-enabling).
        /// </summary>
        [Test]
        public static void SetDiaryGenerationEnabledTogglesAndGates()
        {
            PawnDiarySettings settings = PawnDiaryMod.Settings;

            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetDiaryGenerationEnabled(null, false),
                "SetDiaryGenerationEnabled(null) should be false.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetDiaryGenerationEnabled(ineligiblePawn, true),
                "SetDiaryGenerationEnabled should be false for a base-ineligible pawn.");

            // Observable round-trip on the eligible colonist (SetUp left it enabled).
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.SetDiaryGenerationEnabled(eligiblePawn, false),
                "Disabling generation on an eligible colonist should succeed.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.IsDiaryGenerationEnabled(eligiblePawn),
                "The pawn's generation flag should read false after disabling it.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.SetDiaryGenerationEnabled(eligiblePawn, true),
                "Re-enabling generation on an eligible colonist should succeed.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsDiaryGenerationEnabled(eligiblePawn),
                "The pawn's generation flag should read true after re-enabling it.");

            // Master-switch gate: the write is refused and the saved flag is untouched.
            settings.allowExternalIntegrations = false;
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetDiaryGenerationEnabled(eligiblePawn, false),
                "SetDiaryGenerationEnabled should be refused while the master switch is off.");
            settings.allowExternalIntegrations = true;
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsDiaryGenerationEnabled(eligiblePawn),
                "A refused (gated) write must not have changed the saved generation flag.");
        }

        /// <summary>
        /// §7.1. SetWritingStyleOverride / ResetWritingStyleOverride: a blank sourceId, a null pawn, and a
        /// base-ineligible pawn are all refused with no state written; a valid call on the eligible
        /// colonist persists (returns true) and is then cleared by Reset; and the master switch gates the
        /// SET route. The override lives on the pawn's diary record, which the harness scrubs; a reset
        /// cleanup is also registered.
        /// </summary>
        [Test]
        public static void WritingStyleOverrideCoversNullBlankIneligibleValidAndGate()
        {
            PawnDiarySettings settings = PawnDiaryMod.Settings;
            scope.RegisterCleanup(() => PawnDiaryApi.ResetWritingStyleOverride(eligiblePawn, TestSourceId));

            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetWritingStyleOverride(eligiblePawn, "   ", StyleRule),
                "SetWritingStyleOverride with a blank sourceId should be refused.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetWritingStyleOverride(null, TestSourceId, StyleRule),
                "SetWritingStyleOverride with a null pawn should be refused.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetWritingStyleOverride(ineligiblePawn, TestSourceId, StyleRule),
                "SetWritingStyleOverride should be refused for a base-ineligible pawn.");

            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.SetWritingStyleOverride(eligiblePawn, TestSourceId, StyleRule),
                "A valid SetWritingStyleOverride on an eligible colonist should persist and return true.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.ResetWritingStyleOverride(eligiblePawn, TestSourceId),
                "ResetWritingStyleOverride for the owning source should clear the override and return true.");

            settings.allowExternalIntegrations = false;
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetWritingStyleOverride(eligiblePawn, TestSourceId, StyleRule),
                "SetWritingStyleOverride should be refused while the master switch is off.");
            settings.allowExternalIntegrations = true;
        }

        /// <summary>
        /// §7.1. SetPsychotypeOverride / ResetPsychotypeOverride: mirrors the writing-style contract — a
        /// blank sourceId, a null pawn, and a base-ineligible pawn are refused; a valid call persists and
        /// is cleared by Reset; and the master switch gates the SET route.
        /// </summary>
        [Test]
        public static void PsychotypeOverrideCoversNullBlankIneligibleValidAndGate()
        {
            PawnDiarySettings settings = PawnDiaryMod.Settings;
            scope.RegisterCleanup(() => PawnDiaryApi.ResetPsychotypeOverride(eligiblePawn, TestSourceId));

            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetPsychotypeOverride(eligiblePawn, "   ", PsychotypeRule),
                "SetPsychotypeOverride with a blank sourceId should be refused.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetPsychotypeOverride(null, TestSourceId, PsychotypeRule),
                "SetPsychotypeOverride with a null pawn should be refused.");
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetPsychotypeOverride(ineligiblePawn, TestSourceId, PsychotypeRule),
                "SetPsychotypeOverride should be refused for a base-ineligible pawn.");

            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.SetPsychotypeOverride(eligiblePawn, TestSourceId, PsychotypeRule),
                "A valid SetPsychotypeOverride on an eligible colonist should persist and return true.");
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.ResetPsychotypeOverride(eligiblePawn, TestSourceId),
                "ResetPsychotypeOverride for the owning source should clear the override and return true.");

            settings.allowExternalIntegrations = false;
            PawnDiaryRimTestScope.Require(
                !PawnDiaryApi.SetPsychotypeOverride(eligiblePawn, TestSourceId, PsychotypeRule),
                "SetPsychotypeOverride should be refused while the master switch is off.");
            settings.allowExternalIntegrations = true;
        }

        /// <summary>
        /// §7.1. The entry-status listener registry: a blank id and a null listener are safe no-ops (no
        /// throw), and a valid register/unregister pair on the process-global registry completes cleanly.
        /// A defensive unregister cleanup is registered so the process-global registry is left exactly as
        /// found even if an assertion throws first.
        /// </summary>
        [Test]
        public static void EntryStatusListenerRegisterUnregisterIsSafe()
        {
            const string listenerId = "pawndiary.rimtest.apisurface.listener";

            // Invalid input is swallowed by the API's guards; the assertion is simply that these do not
            // throw and do not disturb readiness.
            PawnDiaryApi.RegisterEntryStatusListener("   ", s => { });
            PawnDiaryApi.RegisterEntryStatusListener(listenerId, null);
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsReady, "The API should still be ready after rejected listener registrations.");

            // Valid register + unregister round-trip on the process-global registry.
            scope.RegisterCleanup(() => PawnDiaryApi.UnregisterEntryStatusListener(listenerId));
            PawnDiaryApi.RegisterEntryStatusListener(listenerId, s => { });
            PawnDiaryApi.UnregisterEntryStatusListener(listenerId);
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsReady, "The API should still be ready after a listener register/unregister pair.");
        }

        /// <summary>
        /// §7.1. RegisterPawnContextProvider rejects a blank id and a null provider as safe no-ops. There
        /// is no public unregister for this add/replace-only runtime registry, so this suite intentionally
        /// does not perform a live registration (which would persist a provider into the developer's
        /// process); it verifies only the leak-free guard behavior.
        /// </summary>
        [Test]
        public static void RegisterPawnContextProviderRejectsInvalidInputWithoutLeaking()
        {
            PawnDiaryApi.RegisterPawnContextProvider("   ", p => null);
            PawnDiaryApi.RegisterPawnContextProvider("pawndiary.rimtest.apisurface.provider", null);
            PawnDiaryRimTestScope.Require(
                PawnDiaryApi.IsReady,
                "The API should still be ready after rejected pawn-context provider registrations.");
        }

        /// <summary>
        /// §7.1. The three submit routes swallow a null request without throwing and record nothing:
        /// SubmitEvent reports InvalidRequest, and the handle-returning SubmitPromptEntry / SubmitDirectEntry
        /// return a not-recorded result. No new diary event referencing a test pawn is created.
        /// </summary>
        [Test]
        public static void SubmitRoutesRejectNullRequestSafely()
        {
            SubmitEventOutcome outcome = SubmitEventOutcome.Recorded;
            scope.RequireNoNewEvent(() => PawnDiaryApi.SubmitEvent(null, out outcome));
            PawnDiaryRimTestScope.Require(
                outcome == SubmitEventOutcome.InvalidRequest,
                "SubmitEvent(null) should report InvalidRequest, but reported " + outcome + ".");

            DiaryEventSubmissionResult promptResult = null;
            scope.RequireNoNewEvent(() => promptResult = PawnDiaryApi.SubmitPromptEntry(null));
            PawnDiaryRimTestScope.Require(
                promptResult != null && !promptResult.recorded,
                "SubmitPromptEntry(null) should return a not-recorded result.");

            DiaryEventSubmissionResult directResult = null;
            scope.RequireNoNewEvent(() => directResult = PawnDiaryApi.SubmitDirectEntry(null));
            PawnDiaryRimTestScope.Require(
                directResult != null && !directResult.recorded,
                "SubmitDirectEntry(null) should return a not-recorded result.");
        }

        // ----- test helpers -----------------------------------------------------------------------

        /// <summary>
        /// Generates a factionless humanlike adult (never spawned, no gear, no relations). Because it is
        /// not a colonist it fails Pawn Diary's base owner eligibility, so every gated API call rejects it
        /// and none can materialize a diary record for it. Registered for destruction in teardown; it is
        /// not one of the harness's tracked scope pawns.
        /// </summary>
        private static Pawn CreateIneligiblePawn()
        {
            PawnGenerationRequest request = new PawnGenerationRequest(
                PawnKindDefOf.Colonist,
                faction: null,
                context: PawnGenerationContext.NonPlayer,
                forceGenerateNewPawn: true,
                canGeneratePawnRelations: false,
                allowPregnant: false,
                allowAddictions: false,
                fixedBiologicalAge: 30f,
                developmentalStages: DevelopmentalStage.Adult,
                forceNoGear: true);
            Pawn pawn = PawnGenerator.GeneratePawn(request);
            if (pawn == null)
            {
                throw new AssertionException("RimWorld failed to generate the ineligible test pawn.");
            }

            if (DiaryGameComponent.IsDiaryEligible(pawn))
            {
                // Defensive: the factionless pawn must not be base-eligible, or the "ineligible" cases
                // would silently pass for the wrong reason.
                pawn.Destroy(DestroyMode.Vanish);
                throw new AssertionException("The intended-ineligible test pawn was unexpectedly diary-eligible.");
            }

            scope.RegisterCleanup(() =>
            {
                if (pawn != null && !pawn.Destroyed)
                {
                    pawn.Destroy(DestroyMode.Vanish);
                }
            });

            return pawn;
        }
    }
}
