#requires -Version 5.1

<#
.SYNOPSIS
Regenerates the source-backed XML Def reference in repowiki/.

.DESCRIPTION
The hand-written wiki explains behavior, while this script owns the mechanical inventory of the
current XML Def files. It parses every XML file below 1.6/Defs, resolves English DefInjected labels
when available, locates matching C# Def declarations below Source, and writes:

- the XML Definition System landing page;
- the Generated Def Reference index;
- one generated reference page per XML Def type.

Use -Check in validation jobs to fail when committed generated pages differ from the current source.
The script never touches pages outside its generated landing page and generated-reference folder.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File tools/generate-xml-def-wiki.ps1

.EXAMPLE
powershell -ExecutionPolicy Bypass -File tools/generate-xml-def-wiki.ps1 -Check
#>

[CmdletBinding()]
param(
    [string]$RepositoryRoot = '',
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$generatedMarker = '<!-- Generated by tools/generate-xml-def-wiki.ps1; do not edit by hand. -->'
if ([string]::IsNullOrWhiteSpace($RepositoryRoot))
{
    $RepositoryRoot = Split-Path -Parent $PSScriptRoot
}
$repositoryRootPath = (Resolve-Path -LiteralPath $RepositoryRoot).Path
$defsRoot = Join-Path $repositoryRootPath '1.6\Defs'
$sourceRoot = Join-Path $repositoryRootPath 'Source'
$englishDefInjectedRoot = Join-Path $repositoryRootPath 'Languages\English\DefInjected'
$xmlWikiRoot = Join-Path $repositoryRootPath 'repowiki\en\content\Configuration & Customization\XML Definition System'
$xmlLandingPath = Join-Path $xmlWikiRoot 'XML Definition System.md'
$generatedReferenceRoot = Join-Path $xmlWikiRoot 'Generated Def Reference'
$generatedReferenceIndexPath = Join-Path $generatedReferenceRoot 'Generated Def Reference.md'

foreach ($requiredPath in @($defsRoot, $sourceRoot, $englishDefInjectedRoot, $xmlWikiRoot))
{
    if (-not (Test-Path -LiteralPath $requiredPath))
    {
        throw "Required path does not exist: $requiredPath"
    }
}

function Get-RepositoryRelativePath
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $fullPath = [IO.Path]::GetFullPath($Path)
    $rootWithSeparator = $repositoryRootPath.TrimEnd('\', '/') + [IO.Path]::DirectorySeparatorChar
    if (-not $fullPath.StartsWith($rootWithSeparator, [StringComparison]::OrdinalIgnoreCase))
    {
        throw "Path is outside the repository: $fullPath"
    }

    return $fullPath.Substring($rootWithSeparator.Length).Replace('\', '/')
}

function Read-XmlDocument
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $settings = New-Object Xml.XmlReaderSettings
    $settings.DtdProcessing = [Xml.DtdProcessing]::Prohibit
    $settings.XmlResolver = $null

    $reader = [Xml.XmlReader]::Create($Path, $settings)
    try
    {
        $document = New-Object Xml.XmlDocument
        $document.XmlResolver = $null
        $document.Load($reader)
        return $document
    }
    finally
    {
        $reader.Dispose()
    }
}

function Get-ElementChildren
{
    param([Parameter(Mandatory = $true)][Xml.XmlNode]$Node)

    return @($Node.ChildNodes | Where-Object {
        $_.NodeType -eq [Xml.XmlNodeType]::Element
    })
}

function Get-ChildText
{
    param(
        [Parameter(Mandatory = $true)][Xml.XmlElement]$Element,
        [Parameter(Mandatory = $true)][string]$ChildName
    )

    $child = $Element.SelectSingleNode("./$ChildName")
    if ($null -eq $child)
    {
        return ''
    }

    return $child.InnerText.Trim()
}

function ConvertTo-MarkdownCell
{
    param([AllowNull()][string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value))
    {
        return '—'
    }

    $clean = [Text.RegularExpressions.Regex]::Replace($Value, '\s+', ' ').Trim()
    $clean = $clean.Replace('|', '\|').Replace('`', '&#96;')
    return $clean
}

function Get-ObservedFieldShape
{
    param([Parameter(Mandatory = $true)][Xml.XmlElement]$Element)

    $children = @(Get-ElementChildren -Node $Element)
    if ($children.Count -eq 0)
    {
        return 'scalar'
    }

    $nonListChildren = @($children | Where-Object { $_.LocalName -ne 'li' })
    if ($nonListChildren.Count -eq 0)
    {
        return 'list'
    }

    return 'object'
}

function Get-SafePageFileName
{
    param(
        [Parameter(Mandatory = $true)][string]$TypeName,
        [Parameter(Mandatory = $true)][hashtable]$ShortNameCounts
    )

    $shortName = ($TypeName -split '\.')[-1]
    $baseName = if ($ShortNameCounts[$shortName] -gt 1)
    {
        $TypeName.Replace('.', '-')
    }
    else
    {
        $shortName
    }

    $invalidPattern = '[' + [Text.RegularExpressions.Regex]::Escape(
        [string]::Join('', [IO.Path]::GetInvalidFileNameChars())) + ']'
    $safeName = [Text.RegularExpressions.Regex]::Replace($baseName, $invalidPattern, '-')
    return "$safeName.md"
}

function Get-SourceFingerprint
{
    param([Parameter(Mandatory = $true)][IO.FileInfo[]]$Files)

    $builder = New-Object Text.StringBuilder
    foreach ($file in @($Files | Sort-Object FullName))
    {
        $relativePath = Get-RepositoryRelativePath -Path $file.FullName
        $content = [IO.File]::ReadAllText($file.FullName).Replace("`r`n", "`n").Replace("`r", "`n")
        [void]$builder.Append($relativePath).Append("`n").Append($content).Append("`n")
    }

    $utf8 = New-Object Text.UTF8Encoding($false)
    $sha256 = [Security.Cryptography.SHA256]::Create()
    try
    {
        $hash = $sha256.ComputeHash($utf8.GetBytes($builder.ToString()))
        return ([BitConverter]::ToString($hash).Replace('-', '').ToLowerInvariant()).Substring(0, 16)
    }
    finally
    {
        $sha256.Dispose()
    }
}

function Normalize-GeneratedText
{
    param([Parameter(Mandatory = $true)][string]$Content)

    return $Content.Replace("`r`n", "`n").Replace("`r", "`n").TrimEnd() + "`n"
}

function Write-Utf8NoBom
{
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    $parent = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $parent))
    {
        [void](New-Item -ItemType Directory -Path $parent -Force)
    }

    $utf8 = New-Object Text.UTF8Encoding($false)
    [IO.File]::WriteAllText($Path, (Normalize-GeneratedText -Content $Content), $utf8)
}

# Def text is commonly localized through DefInjected instead of a literal <label> in 1.6/Defs.
# Build a single lookup so each generated row can show the shipped English label when one exists.
$englishValues = @{}
foreach ($languageFile in @(Get-ChildItem -LiteralPath $englishDefInjectedRoot -Recurse -File -Filter '*.xml' |
    Sort-Object FullName))
{
    $languageDocument = Read-XmlDocument -Path $languageFile.FullName
    if ($null -eq $languageDocument.DocumentElement -or
        $languageDocument.DocumentElement.LocalName -ne 'LanguageData')
    {
        continue
    }

    foreach ($entry in @(Get-ElementChildren -Node $languageDocument.DocumentElement))
    {
        $englishValues[$entry.LocalName] = $entry.InnerText.Trim()
    }
}

$xmlFiles = @(Get-ChildItem -LiteralPath $defsRoot -Recurse -File -Filter '*.xml' | Sort-Object FullName)
$records = New-Object System.Collections.Generic.List[object]
$parsedDefFiles = New-Object System.Collections.Generic.List[object]

foreach ($xmlFile in $xmlFiles)
{
    $document = Read-XmlDocument -Path $xmlFile.FullName
    if ($null -eq $document.DocumentElement -or $document.DocumentElement.LocalName -ne 'Defs')
    {
        continue
    }

    $relativePath = Get-RepositoryRelativePath -Path $xmlFile.FullName
    [void]$parsedDefFiles.Add($xmlFile)
    foreach ($element in @(Get-ElementChildren -Node $document.DocumentElement))
    {
        $typeName = $element.LocalName
        $shortTypeName = ($typeName -split '\.')[-1]
        $defName = Get-ChildText -Element $element -ChildName 'defName'
        $label = Get-ChildText -Element $element -ChildName 'label'
        if ([string]::IsNullOrWhiteSpace($label) -and -not [string]::IsNullOrWhiteSpace($defName))
        {
            $labelKey = "$defName.label"
            if ($englishValues.ContainsKey($labelKey))
            {
                $label = [string]$englishValues[$labelKey]
            }
        }

        $abstractName = $element.GetAttribute('Name')
        $isAbstract = [string]::Equals(
            $element.GetAttribute('Abstract'),
            'True',
            [StringComparison]::OrdinalIgnoreCase)
        $displayName = if (-not [string]::IsNullOrWhiteSpace($defName))
        {
            $defName
        }
        elseif (-not [string]::IsNullOrWhiteSpace($abstractName))
        {
            "abstract: $abstractName"
        }
        else
        {
            'unnamed record'
        }

        [void]$records.Add([pscustomobject]@{
            TypeName = $typeName
            ShortTypeName = $shortTypeName
            DefName = $defName
            DisplayName = $displayName
            Label = $label
            ParentName = $element.GetAttribute('ParentName')
            AbstractName = $abstractName
            IsAbstract = $isAbstract
            XmlPath = $relativePath
            Element = $element
        })
    }
}

if ($records.Count -eq 0)
{
    throw "No Def records were found below $defsRoot"
}

$sourceFiles = @(Get-ChildItem -LiteralPath $sourceRoot -Recurse -File -Filter '*.cs' | Sort-Object FullName)
$sourceContents = @{}
foreach ($sourceFile in $sourceFiles)
{
    $sourceContents[$sourceFile.FullName] = [IO.File]::ReadAllText($sourceFile.FullName)
}

$typeNames = @($records | Select-Object -ExpandProperty TypeName -Unique | Sort-Object)
$shortNameCounts = @{}
foreach ($typeName in $typeNames)
{
    $shortName = ($typeName -split '\.')[-1]
    if (-not $shortNameCounts.ContainsKey($shortName))
    {
        $shortNameCounts[$shortName] = 0
    }
    $shortNameCounts[$shortName]++
}

$implementationPathsByType = @{}
foreach ($typeName in $typeNames)
{
    $shortName = ($typeName -split '\.')[-1]
    $pattern = '\bclass\s+' + [Text.RegularExpressions.Regex]::Escape($shortName) + '\b'
    $matches = New-Object System.Collections.Generic.List[string]
    foreach ($sourceFile in $sourceFiles)
    {
        if ([Text.RegularExpressions.Regex]::IsMatch($sourceContents[$sourceFile.FullName], $pattern))
        {
            [void]$matches.Add((Get-RepositoryRelativePath -Path $sourceFile.FullName))
        }
    }
    $implementationPathsByType[$typeName] = @($matches | Sort-Object -Unique)
}

$implementationFiles = @($implementationPathsByType.Values |
    ForEach-Object { $_ } |
    Sort-Object -Unique |
    ForEach-Object { Get-Item -LiteralPath (Join-Path $repositoryRootPath $_) })
$sourceFingerprint = Get-SourceFingerprint -Files @($parsedDefFiles + $implementationFiles)
$namedRecordCount = @($records | Where-Object { -not [string]::IsNullOrWhiteSpace($_.DefName) }).Count
$abstractRecordCount = @($records | Where-Object { $_.IsAbstract }).Count

$desiredPages = @{}

$index = New-Object Text.StringBuilder
[void]$index.AppendLine($generatedMarker)
[void]$index.AppendLine()
[void]$index.AppendLine('# Generated Def Reference')
[void]$index.AppendLine()
[void]$index.AppendLine('This reference is generated from the current `1.6/Defs/**/*.xml` files and matching')
[void]$index.AppendLine('declarations under `Source/`. It inventories what is actually shipped; hand-written')
[void]$index.AppendLine('behavior pages remain responsible for explaining runtime semantics.')
[void]$index.AppendLine()
[void]$index.AppendLine("- Source fingerprint: ``$sourceFingerprint``")
[void]$index.AppendLine("- Parsed XML files: **$($parsedDefFiles.Count)**")
[void]$index.AppendLine("- XML Def types: **$($typeNames.Count)**")
[void]$index.AppendLine("- Named Def instances: **$namedRecordCount**")
[void]$index.AppendLine("- Abstract XML parents: **$abstractRecordCount**")
[void]$index.AppendLine()
[void]$index.AppendLine('[Back to XML Definition System](../XML%20Definition%20System.md)')
[void]$index.AppendLine()
[void]$index.AppendLine('## Def types')
[void]$index.AppendLine()
[void]$index.AppendLine('| XML type | Records | XML files | C# declaration |')
[void]$index.AppendLine('|---|---:|---:|---|')

foreach ($typeName in $typeNames)
{
    $typeRecords = @($records | Where-Object { $_.TypeName -eq $typeName } |
        Sort-Object DisplayName, XmlPath)
    $fileCount = @($typeRecords | Select-Object -ExpandProperty XmlPath -Unique).Count
    $pageFileName = Get-SafePageFileName -TypeName $typeName -ShortNameCounts $shortNameCounts
    $implementations = @($implementationPathsByType[$typeName])
    $implementationCell = if ($implementations.Count -eq 0)
    {
        'RimWorld/Verse'
    }
    else
    {
        @($implementations | ForEach-Object {
            $label = Split-Path -Leaf $_
            "[$label](../../../../../../$_)"
        }) -join '<br>'
    }
    [void]$index.AppendLine(
        "| [``$(ConvertTo-MarkdownCell -Value $typeName)``]($pageFileName) | $($typeRecords.Count) | $fileCount | $implementationCell |")
}

$desiredPages[$generatedReferenceIndexPath] = $index.ToString()

foreach ($typeName in $typeNames)
{
    $typeRecords = @($records | Where-Object { $_.TypeName -eq $typeName } |
        Sort-Object DisplayName, XmlPath)
    $pageFileName = Get-SafePageFileName -TypeName $typeName -ShortNameCounts $shortNameCounts
    $pagePath = Join-Path $generatedReferenceRoot $pageFileName
    $implementations = @($implementationPathsByType[$typeName])
    $sourcePaths = @($typeRecords | Select-Object -ExpandProperty XmlPath -Unique | Sort-Object)

    $page = New-Object Text.StringBuilder
    [void]$page.AppendLine($generatedMarker)
    [void]$page.AppendLine()
    [void]$page.AppendLine("# $(($typeName -split '\.')[-1])")
    [void]$page.AppendLine()
    [void]$page.AppendLine("- XML element: ``$typeName``")
    [void]$page.AppendLine("- Records in the shipped Def catalog: **$($typeRecords.Count)**")
    [void]$page.AppendLine("- Source fingerprint: ``$sourceFingerprint``")
    if ($implementations.Count -gt 0)
    {
        $implementationLinks = @($implementations | ForEach-Object {
            $label = Split-Path -Leaf $_
            "[$label](../../../../../../$_)"
        }) -join ', '
        [void]$page.AppendLine("- C# declaration: $implementationLinks")
    }
    else
    {
        [void]$page.AppendLine('- C# declaration: provided by RimWorld/Verse rather than Pawn Diary.')
    }
    [void]$page.AppendLine()
    [void]$page.AppendLine('[Generated reference index](Generated%20Def%20Reference.md) · [XML Definition System](../XML%20Definition%20System.md)')
    [void]$page.AppendLine()
    [void]$page.AppendLine('## Source XML')
    [void]$page.AppendLine()
    foreach ($sourcePath in $sourcePaths)
    {
        $label = Split-Path -Leaf $sourcePath
        [void]$page.AppendLine("- [$label](../../../../../../$sourcePath)")
    }
    [void]$page.AppendLine()
    [void]$page.AppendLine('## Instances')
    [void]$page.AppendLine()
    [void]$page.AppendLine('| defName or parent | English label | ParentName | Source |')
    [void]$page.AppendLine('|---|---|---|---|')
    foreach ($record in $typeRecords)
    {
        $sourceLabel = Split-Path -Leaf $record.XmlPath
        $sourceLink = "[$sourceLabel](../../../../../../$($record.XmlPath))"
        [void]$page.AppendLine(
            "| ``$(ConvertTo-MarkdownCell -Value $record.DisplayName)`` | " +
            "$(ConvertTo-MarkdownCell -Value $record.Label) | " +
            "``$(ConvertTo-MarkdownCell -Value $record.ParentName)`` | $sourceLink |")
    }

    $fieldObservations = New-Object System.Collections.Generic.List[object]
    foreach ($record in $typeRecords)
    {
        $seenFields = @{}
        foreach ($field in @(Get-ElementChildren -Node $record.Element))
        {
            if ($field.LocalName -eq 'defName' -or $field.LocalName -eq 'label')
            {
                continue
            }
            if ($seenFields.ContainsKey($field.LocalName))
            {
                continue
            }
            $seenFields[$field.LocalName] = $true
            [void]$fieldObservations.Add([pscustomobject]@{
                FieldName = $field.LocalName
                Shape = Get-ObservedFieldShape -Element $field
            })
        }
    }

    [void]$page.AppendLine()
    [void]$page.AppendLine('## Observed top-level XML fields')
    [void]$page.AppendLine()
    [void]$page.AppendLine('This is an inventory of fields present in the shipped XML, not a replacement for the C# schema.')
    [void]$page.AppendLine('Code fallbacks, inherited fields, and optional extension fields may not appear here.')
    [void]$page.AppendLine()
    [void]$page.AppendLine('| Field | Present on records | Observed shape |')
    [void]$page.AppendLine('|---|---:|---|')
    foreach ($fieldGroup in @($fieldObservations | Group-Object FieldName | Sort-Object Name))
    {
        $shapes = @($fieldGroup.Group | Select-Object -ExpandProperty Shape -Unique | Sort-Object)
        [void]$page.AppendLine(
            "| ``$(ConvertTo-MarkdownCell -Value $fieldGroup.Name)`` | $($fieldGroup.Count) / $($typeRecords.Count) | $($shapes -join ', ') |")
    }

    $desiredPages[$pagePath] = $page.ToString()
}

$landing = New-Object Text.StringBuilder
[void]$landing.AppendLine($generatedMarker)
[void]$landing.AppendLine()
[void]$landing.AppendLine('# XML Definition System')
[void]$landing.AppendLine()
[void]$landing.AppendLine('Pawn Diary keeps tunable policy in RimWorld XML Defs and consumes it through C# Def classes.')
[void]$landing.AppendLine('This page is regenerated from the shipped files so its inventory cannot drift from the repository.')
[void]$landing.AppendLine()
[void]$landing.AppendLine('## Current snapshot')
[void]$landing.AppendLine()
[void]$landing.AppendLine("- Source fingerprint: ``$sourceFingerprint``")
[void]$landing.AppendLine("- Parsed XML files below `1.6/Defs/`: **$($parsedDefFiles.Count)**")
[void]$landing.AppendLine("- XML Def types: **$($typeNames.Count)**")
[void]$landing.AppendLine("- Named Def instances: **$namedRecordCount**")
[void]$landing.AppendLine("- Abstract XML parents: **$abstractRecordCount**")
[void]$landing.AppendLine()
[void]$landing.AppendLine('Open the [Generated Def Reference](Generated%20Def%20Reference/Generated%20Def%20Reference.md)')
[void]$landing.AppendLine('for one live page per Def type, including source files, instances, English labels, C# declarations,')
[void]$landing.AppendLine('and the top-level fields observed in the current XML.')
[void]$landing.AppendLine()
[void]$landing.AppendLine('## Authoritative sources')
[void]$landing.AppendLine()
[void]$landing.AppendLine('- `1.6/Defs/**/*.xml` owns shipped policy and default Def instances.')
[void]$landing.AppendLine('- Matching declarations below `Source/` own the runtime schema; most live in `Source/Defs/`.')
[void]$landing.AppendLine('- `Languages/*/DefInjected/` localizes Def text such as labels, rules, instructions, and prompts.')
[void]$landing.AppendLine('- `Languages/*/Keyed/` localizes player-facing UI and prompt strings that are not Def fields.')
[void]$landing.AppendLine('- `1.6/Patches/` extends vanilla or optional-mod XML; those files use the singular `<Patch>` root.')
[void]$landing.AppendLine()
[void]$landing.AppendLine('## Runtime flow')
[void]$landing.AppendLine()
[void]$landing.AppendLine('```mermaid')
[void]$landing.AppendLine('flowchart LR')
[void]$landing.AppendLine('    XML["1.6/Defs XML"] --> Loader["RimWorld Def loader"]')
[void]$landing.AppendLine('    Localized["DefInjected text"] --> Loader')
[void]$landing.AppendLine('    Loader --> Database["DefDatabase<T>"]')
[void]$landing.AppendLine('    Database --> Accessor["Pawn Diary Def accessors"]')
[void]$landing.AppendLine('    Accessor --> Runtime["capture, planning, prompts, persistence, and UI"]')
[void]$landing.AppendLine('```')
[void]$landing.AppendLine()
[void]$landing.AppendLine('RimWorld loads Defs at startup; Pawn Diary does not parse these files during ordinary gameplay.')
[void]$landing.AppendLine('Consumers query typed Defs or repository accessors, then pass plain values into pure selection and')
[void]$landing.AppendLine('formatting code. The generated reference reports the loaded declarations, not every downstream use.')
[void]$landing.AppendLine()
[void]$landing.AppendLine('## Authoring rules')
[void]$landing.AppendLine()
[void]$landing.AppendLine('- Put prompt policy, thresholds, odds, UI style values, tags, colors, and other tunable behavior in XML.')
[void]$landing.AppendLine('- Use fully-qualified names for Pawn Diary types in XML `Class` or `Type` fields.')
[void]$landing.AppendLine('- Keep `{}`, `[]`, and template tokens out of Def labels; RimWorld validates labels before runtime substitution.')
[void]$landing.AppendLine('- Keep DLC and optional-mod matchers as plain strings where possible. A missing Def then simply never matches.')
[void]$landing.AppendLine('- If XML must reference DLC content directly, add the correct `MayRequire` package guard.')
[void]$landing.AppendLine('- Use `GetNamedSilentFail` plus a null check for optional Def lookups; `GetNamed` throws when content is absent.')
[void]$landing.AppendLine('- Localize Def prose through DefInjected and UI text through Keyed strings.')
[void]$landing.AppendLine()
[void]$landing.AppendLine('## Regeneration')
[void]$landing.AppendLine()
[void]$landing.AppendLine('```powershell')
[void]$landing.AppendLine('powershell -ExecutionPolicy Bypass -File tools/generate-xml-def-wiki.ps1')
[void]$landing.AppendLine('powershell -ExecutionPolicy Bypass -File tools/generate-xml-def-wiki.ps1 -Check')
[void]$landing.AppendLine('```')
[void]$landing.AppendLine()
[void]$landing.AppendLine('The first command refreshes this landing page and the generated reference. `-Check` performs no')
[void]$landing.AppendLine('writes and fails if committed output is missing, stale, or contains an obsolete generated type page.')
[void]$landing.AppendLine()
[void]$landing.AppendLine('## Current XML files')
[void]$landing.AppendLine()
[void]$landing.AppendLine('| File | XML types | Named records | Abstract parents |')
[void]$landing.AppendLine('|---|---|---:|---:|')
foreach ($fileGroup in @($records | Group-Object XmlPath | Sort-Object Name))
{
    $fileRecords = @($fileGroup.Group)
    $types = @($fileRecords | Select-Object -ExpandProperty ShortTypeName -Unique | Sort-Object)
    $namedCount = @($fileRecords | Where-Object { -not [string]::IsNullOrWhiteSpace($_.DefName) }).Count
    $abstractCount = @($fileRecords | Where-Object { $_.IsAbstract }).Count
    $fileLabel = Split-Path -Leaf $fileGroup.Name
    [void]$landing.AppendLine(
        "| [$fileLabel](../../../../../$($fileGroup.Name)) | " +
        "$(@($types | ForEach-Object { ""``$_``"" }) -join ', ') | $namedCount | $abstractCount |")
}
[void]$landing.AppendLine()
[void]$landing.AppendLine('## Topic guides')
[void]$landing.AppendLine()
[void]$landing.AppendLine('- [Tuning Definitions](Tuning%20Definitions.md)')
[void]$landing.AppendLine('- [Context Details](Context%20Details.md)')
[void]$landing.AppendLine('- [Event Windows](Event%20Windows.md)')
[void]$landing.AppendLine('- [Persona Configurations](Persona%20Configurations/Persona%20Configurations.md)')
[void]$landing.AppendLine('- [Prompt Templates](Prompt%20Templates/Prompt%20Templates.md)')
[void]$landing.AppendLine('- [Psychotype System](Psychotype%20System/Psychotype%20System.md)')

$desiredPages[$xmlLandingPath] = $landing.ToString()

$problems = New-Object System.Collections.Generic.List[string]
foreach ($pagePath in @($desiredPages.Keys | Sort-Object))
{
    $expected = Normalize-GeneratedText -Content ([string]$desiredPages[$pagePath])
    if (-not (Test-Path -LiteralPath $pagePath))
    {
        [void]$problems.Add("Missing generated page: $(Get-RepositoryRelativePath -Path $pagePath)")
        continue
    }

    $actual = [IO.File]::ReadAllText($pagePath).Replace("`r`n", "`n").Replace("`r", "`n")
    if ($actual -ne $expected)
    {
        [void]$problems.Add("Stale generated page: $(Get-RepositoryRelativePath -Path $pagePath)")
    }
}

if (Test-Path -LiteralPath $generatedReferenceRoot)
{
    foreach ($existingPage in @(Get-ChildItem -LiteralPath $generatedReferenceRoot -File -Filter '*.md'))
    {
        if (-not $desiredPages.ContainsKey($existingPage.FullName))
        {
            $content = [IO.File]::ReadAllText($existingPage.FullName)
            if ($content.StartsWith($generatedMarker, [StringComparison]::Ordinal))
            {
                [void]$problems.Add("Obsolete generated page: $(Get-RepositoryRelativePath -Path $existingPage.FullName)")
            }
            else
            {
                throw "Refusing to manage an unmarked page in the generated directory: $($existingPage.FullName)"
            }
        }
    }
}

if ($Check)
{
    if ($problems.Count -gt 0)
    {
        throw "XML Def wiki check failed:`n - $($problems -join "`n - ")"
    }

    Write-Output "XML Def wiki is current: $($parsedDefFiles.Count) files, $($typeNames.Count) types, $namedRecordCount named records, fingerprint $sourceFingerprint."
    exit 0
}

if (-not (Test-Path -LiteralPath $generatedReferenceRoot))
{
    [void](New-Item -ItemType Directory -Path $generatedReferenceRoot -Force)
}

foreach ($existingPage in @(Get-ChildItem -LiteralPath $generatedReferenceRoot -File -Filter '*.md'))
{
    if ($desiredPages.ContainsKey($existingPage.FullName))
    {
        continue
    }

    $content = [IO.File]::ReadAllText($existingPage.FullName)
    if (-not $content.StartsWith($generatedMarker, [StringComparison]::Ordinal))
    {
        throw "Refusing to delete an unmarked page in the generated directory: $($existingPage.FullName)"
    }

    Remove-Item -LiteralPath $existingPage.FullName
}

foreach ($pagePath in @($desiredPages.Keys | Sort-Object))
{
    Write-Utf8NoBom -Path $pagePath -Content ([string]$desiredPages[$pagePath])
}

Write-Output "Regenerated XML Def wiki: $($parsedDefFiles.Count) files, $($typeNames.Count) types, $namedRecordCount named records, fingerprint $sourceFingerprint."
